// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

//! HTTP call helpers for /2/activity/subscriptions.
#[allow(unused_imports)]
use crate::x::client::{AuthMode, Client};
#[allow(unused_imports)]
use crate::x::Error;
#[allow(unused_imports)]
use reqwest::Method;

/// GET /2/activity/subscriptions
pub async fn get(
    client: &Client,
    auth: &AuthMode,
    req: &super::get::Request,
) -> Result<super::get::Response, Error> {
    let path = "activity/subscriptions";
    client.send_with_query(auth, Method::GET, path, req, true, false).await
}

/// POST /2/activity/subscriptions
pub async fn post(
    client: &Client,
    auth: &AuthMode,
    req: &super::post::Request,
) -> Result<super::post::Response, Error> {
    let path = "activity/subscriptions";
    client.send(auth, Method::POST, path, req.body.as_ref(), false, false).await
}

/// DELETE /2/activity/subscriptions
pub async fn delete(
    client: &Client,
    auth: &AuthMode,
    req: &super::delete::Request,
) -> Result<super::delete::Response, Error> {
    let path = "activity/subscriptions";
    client.send_with_query(auth, Method::DELETE, path, req, false, false).await
}

