// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

//! HTTP call helpers for /2/tweets/search/webhooks/{webhook_id}.
#[allow(unused_imports)]
use crate::x::client::Client;
#[allow(unused_imports)]
use crate::x::Error;
#[allow(unused_imports)]
use reqwest::Method;

/// POST /2/tweets/search/webhooks/{webhook_id}
pub async fn post(
    client: &Client,
    req: &super::post::Request,
) -> Result<super::post::Response, Error> {
    let path = format!("tweets/search/webhooks/{}", urlencoding::encode(&req.webhook_id.to_string()));
    client.send_with_query(Method::POST, &path, req, false).await
}

/// DELETE /2/tweets/search/webhooks/{webhook_id}
pub async fn delete(
    client: &Client,
    req: &super::delete::Request,
) -> Result<super::delete::Response, Error> {
    let path = format!("tweets/search/webhooks/{}", urlencoding::encode(&req.webhook_id.to_string()));
    client.send::<_, ()>(Method::DELETE, &path, None, false).await
}

