// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

//! HTTP call helpers for /2/openapi.json.
#[allow(unused_imports)]
use crate::x::client::Client;
#[allow(unused_imports)]
use crate::x::Error;
#[allow(unused_imports)]
use reqwest::Method;

/// GET /2/openapi.json
pub async fn get(
    client: &Client,
    _req: &super::get::Request,
) -> Result<super::get::Response, Error> {
    let path = "openapi.json";
    client.send::<_, ()>(Method::GET, path, None, true, false).await
}

