//! X API v2 HTTP client + types + OAuth + X-App config.
//!
//! Hand-written modules cover the cross-cutting bits — error
//! type, HTTP send/cache plumbing, mock client, OAuth 2.0
//! PKCE flow, X-App config loader. The codegen'd endpoint /
//! type / parameter modules ship under [`codegen`] (regenerated
//! by `python x-api-spec/codegen.py`) and are glob-re-exported
//! here so callers can spell paths like
//! `sdk::x::tweets::id::get` directly.

#![allow(non_camel_case_types, non_snake_case, dead_code)]

pub mod auth;
pub mod cache;
pub mod client;
pub mod locker;
pub mod queue;
pub mod serde_helpers;
pub mod types;
pub mod params;
pub mod error;
pub mod mock;

pub mod x_app;
pub mod oauth;

pub use error::Error;

// Spec-derived endpoint module declarations live in codegen.rs and are
// re-exported here. Regenerated by `python x-api-spec/codegen.py`; this
// file stays hand-written so adding/removing endpoints in the spec
// never requires editing mod.rs.
mod codegen;
pub use codegen::*;
