// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

//! HTTP call helpers for /2/users/{id}/public_keys.
#[allow(unused_imports)]
use crate::x::client::Client;
#[allow(unused_imports)]
use crate::x::Error;
#[allow(unused_imports)]
use reqwest::Method;

/// GET /2/users/{id}/public_keys
pub async fn get(
    client: &Client,
    req: &super::get::Request,
) -> Result<super::get::Response, Error> {
    let path = format!("users/{}/public_keys", urlencoding::encode(&req.id.to_string()));
    client.send_with_query(Method::GET, &path, req, true, false).await
}

/// POST /2/users/{id}/public_keys
pub async fn post(
    client: &Client,
    req: &super::post::Request,
) -> Result<super::post::Response, Error> {
    let path = format!("users/{}/public_keys", urlencoding::encode(&req.id.to_string()));
    client.send(Method::POST, &path, Some(&req.body), false, false).await
}

