// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

//! HTTP call helpers for /2/account_activity/webhooks/{webhook_id}/subscriptions/all.
#[allow(unused_imports)]
use crate::x::client::Client;
#[allow(unused_imports)]
use crate::x::Error;
#[allow(unused_imports)]
use reqwest::Method;

/// GET /2/account_activity/webhooks/{webhook_id}/subscriptions/all
pub async fn get(
    client: &Client,
    req: &super::get::Request,
) -> Result<super::get::Response, Error> {
    let path = format!("account_activity/webhooks/{}/subscriptions/all", urlencoding::encode(&req.webhook_id.to_string()));
    client.send::<_, ()>(Method::GET, &path, None, true).await
}

/// POST /2/account_activity/webhooks/{webhook_id}/subscriptions/all
pub async fn post(
    client: &Client,
    req: &super::post::Request,
) -> Result<super::post::Response, Error> {
    let path = format!("account_activity/webhooks/{}/subscriptions/all", urlencoding::encode(&req.webhook_id.to_string()));
    client.send(Method::POST, &path, req.body.as_ref(), false).await
}

