// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

//! HTTP call helpers for /2/tweets/search/webhooks.
#[allow(unused_imports)]
use crate::x::http::Http;
#[allow(unused_imports)]
use crate::x::Error;
#[allow(unused_imports)]
use reqwest::Method;

/// GET /2/tweets/search/webhooks
pub async fn get(
    http: &Http,
    _req: &super::get::Request,
    cache: bool,
) -> Result<super::get::Response, Error> {
    let _ = cache;
    let path = "tweets/search/webhooks";
    http.send::<_, ()>(Method::GET, path, None).await
}

