// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

//! HTTP call helpers for /2/chat/media/upload/initialize.
#[allow(unused_imports)]
use crate::x::client::{AuthMode, Client};
#[allow(unused_imports)]
use crate::x::Error;
#[allow(unused_imports)]
use reqwest::Method;

/// POST /2/chat/media/upload/initialize
pub async fn post(
    client: &Client,
    auth: &AuthMode,
    req: &super::post::Request,
) -> Result<super::post::Response, Error> {
    let path = "chat/media/upload/initialize";
    client.send(auth, Method::POST, path, Some(&req.body), false, false).await
}

