// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

#[allow(unused_imports)]
use super::*;
#[allow(unused_imports)]
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChatSendTypingIndicatorResponse {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub data: Option<ChatSendTypingIndicatorResponseData>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub errors: Option<Vec<ProblemUnion>>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChatSendTypingIndicatorResponseData {
    /// Whether the typing indicator was sent successfully.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub success: Option<bool>,
}
