// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

#[allow(unused_imports)]
use super::*;
#[allow(unused_imports)]
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Media {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub height: Option<MediaHeight>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub media_key: Option<MediaKey>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub type_: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub width: Option<MediaWidth>,
}

/// Polymorphic view of [`Media`] discriminated by `type`.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum MediaUnion {
    #[serde(rename = "animated_gif")]
    AnimatedGif(AnimatedGif),
    #[serde(rename = "photo")]
    Photo(Photo),
    #[serde(rename = "video")]
    Video(Video),
}
