// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

#[allow(unused_imports)]
use super::*;
#[allow(unused_imports)]
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SharedInfo {
    /// Indicates if the media is shared in direct messages
    pub shared: bool,
}
