// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

#[allow(unused_imports)]
use super::*;
#[allow(unused_imports)]
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UsersRetweetsDeleteResponse {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub data: Option<UsersRetweetsDeleteResponseData>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub errors: Option<Vec<ProblemUnion>>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UsersRetweetsDeleteResponseData {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub retweeted: Option<bool>,
}
