// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

//! HTTP call helpers for /2/chat/conversations/group/initialize.
#[allow(unused_imports)]
use crate::x::client::Client;
#[allow(unused_imports)]
use crate::x::Error;
#[allow(unused_imports)]
use reqwest::Method;

/// POST /2/chat/conversations/group/initialize
pub async fn post(
    client: &Client,
    _req: &super::post::Request,
) -> Result<super::post::Response, Error> {
    let path = "chat/conversations/group/initialize";
    client.send::<_, ()>(Method::POST, path, None, false).await
}

