// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

//! HTTP call helpers for /2/users/{id}/bookmarks/folders/{folder_id}.
#[allow(unused_imports)]
use crate::x::client::{AuthMode, Client};
#[allow(unused_imports)]
use crate::x::Error;
#[allow(unused_imports)]
use reqwest::Method;

/// GET /2/users/{id}/bookmarks/folders/{folder_id}
pub async fn get(
    client: &Client,
    auth: &AuthMode,
    req: &super::get::Request,
) -> Result<super::get::Response, Error> {
    let path = format!("users/{}/bookmarks/folders/{}", urlencoding::encode(&req.id.to_string()), urlencoding::encode(&req.folder_id.to_string()));
    client.send::<_, ()>(auth, Method::GET, &path, None, true, false).await
}

