// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

//! HTTP call helpers for /2/connections.
#[allow(unused_imports)]
use crate::x::http::Http;
#[allow(unused_imports)]
use crate::x::Error;
#[allow(unused_imports)]
use reqwest::Method;

/// GET /2/connections
pub async fn get(
    http: &Http,
    req: &super::get::Request,
    cache: bool,
) -> Result<super::get::Response, Error> {
    let _ = cache;
    let path = "connections";
    http.send_with_query(Method::GET, path, req).await
}

/// DELETE /2/connections
pub async fn delete(
    http: &Http,
    req: &super::delete::Request,
    cache: bool,
) -> Result<super::delete::Response, Error> {
    let _ = cache;
    let path = "connections";
    http.send(Method::DELETE, path, Some(&req.body)).await
}

