// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

//! HTTP call helpers for /2/webhooks/{webhook_id}.
#[allow(unused_imports)]
use crate::x::client::Client;
#[allow(unused_imports)]
use crate::x::Error;
#[allow(unused_imports)]
use reqwest::Method;

/// PUT /2/webhooks/{webhook_id}
pub async fn put(
    client: &Client,
    req: &super::put::Request,
) -> Result<super::put::Response, Error> {
    let path = format!("webhooks/{}", urlencoding::encode(&req.webhook_id.to_string()));
    client.send::<_, ()>(Method::PUT, &path, None, false).await
}

/// DELETE /2/webhooks/{webhook_id}
pub async fn delete(
    client: &Client,
    req: &super::delete::Request,
) -> Result<super::delete::Response, Error> {
    let path = format!("webhooks/{}", urlencoding::encode(&req.webhook_id.to_string()));
    client.send::<_, ()>(Method::DELETE, &path, None, false).await
}

