// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

//! HTTP call helpers for /2/webhooks/{webhook_id}.
#[allow(unused_imports)]
use crate::x::client::{AuthMode, Client};
#[allow(unused_imports)]
use crate::x::Error;
#[allow(unused_imports)]
use reqwest::Method;

/// PUT /2/webhooks/{webhook_id}
pub async fn put(
    client: &Client,
    auth: &AuthMode,
    req: &super::put::Request,
) -> Result<super::put::Response, Error> {
    let path = format!(
        "webhooks/{}",
        urlencoding::encode(&req.webhook_id.to_string())
    );
    client
        .send::<_, ()>(auth, Method::PUT, &path, None, false, false)
        .await
}

/// DELETE /2/webhooks/{webhook_id}
pub async fn delete(
    client: &Client,
    auth: &AuthMode,
    req: &super::delete::Request,
) -> Result<super::delete::Response, Error> {
    let path = format!(
        "webhooks/{}",
        urlencoding::encode(&req.webhook_id.to_string())
    );
    client
        .send::<_, ()>(auth, Method::DELETE, &path, None, false, false)
        .await
}
