// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

//! HTTP call helpers for /2/activity/subscriptions.
#[allow(unused_imports)]
use crate::x::http::Http;
#[allow(unused_imports)]
use crate::x::Error;
#[allow(unused_imports)]
use reqwest::Method;

/// GET /2/activity/subscriptions
pub async fn get(
    http: &Http,
    req: &super::get::Request,
    cache: bool,
) -> Result<super::get::Response, Error> {
    let path = "activity/subscriptions";
    http.send_with_query(Method::GET, path, req, cache).await
}

/// POST /2/activity/subscriptions
pub async fn post(
    http: &Http,
    req: &super::post::Request,
    cache: bool,
) -> Result<super::post::Response, Error> {
    let path = "activity/subscriptions";
    http.send(Method::POST, path, req.body.as_ref(), cache).await
}

/// DELETE /2/activity/subscriptions
pub async fn delete(
    http: &Http,
    req: &super::delete::Request,
    cache: bool,
) -> Result<super::delete::Response, Error> {
    let path = "activity/subscriptions";
    http.send_with_query(Method::DELETE, path, req, cache).await
}

